---
- hosts: localhost
  vars:
     subscription_id : 5a82d8c6-16b8-4f87-b9de-c12f7e5b3146
     client_id : ed87847e-b76d-4184-b878-434f68caa07e
     secret : 60KTrgYEH_2V.S-3iT0l-B0Q8~jihmHX2Y
     tenant : fccbfa94-4769-4210-a95d-2ac76d452d92
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       name: myResourceGroup
       location: westus
